### ISSUE TITLE
'-'

### ISSUE THREAD

**Issue by ghost** [Pedro-Souza/Scripts-Python#2]
why you not use:

``` python
def potencia(self):
    return pow(self.n1, self.n2)
```

**Comment by Pedro-Souza** [comment]
Where?

**Comment by ghost** [comment]
https://github.com/Pedro-Souza/My-Codes/blob/master/calculate.py#L24-L25

**Comment by Pedro-Souza** [comment]
Python have *\* already have high so no need to import the pow.

OBS: My English is terrible.

**Comment by ghost** [comment]
:)
